version: '3.8'

services:

 
  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"  # Exponemos el puerto de MongoDB a la máquina local
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"  # Exponemos Mongo Express en el puerto 8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    networks:
      - backend

volumes:
  mongo-data:

networks:
  backend:
    driver: bridge
